services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: weight-tracker-mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_INITDB}
    command: mongod --auth
    restart: unless-stopped
    networks:
      - weight-tracker-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${API_NODE_ENV:-production}
        - PORT=${API_PORT:-3001}  # Align with Dockerfile
        - MONGODB_URI=${MONGODB_URI}
        - CORS_ORIGIN=${API_CORS_ORIGIN}
    container_name: weight-tracker-backend
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"  # Consistent port mapping
    volumes:
      - ./backend/uploads:/app/uploads:rw
    environment:
      - NODE_ENV=${API_NODE_ENV:-production}
      - PORT=${API_PORT:-3001}
      - MONGODB_URI=${MONGODB_URI}
      - CORS_ORIGIN=${API_CORS_ORIGIN}
      - HOST=${API_HOST}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - weight-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT:-3001}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend web application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}  # Backend address
        - VITE_API_ENDPOINT=${API_ENDPOINT}
        - VITE_API_TARGET=${VITE_API_TARGET}
    container_name: weight-tracker-frontend
    ports:
      - "${UI_PORT:-80}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://backend:3001}  # For nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - weight-tracker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  weight-tracker-network:
    driver: bridge

volumes:
  mongodb_data: